image:
  file: .gitpod.Dockerfile

tasks:
    - init: dep ensure
    - name: Download Nextflow Tutorial
      command: |
        echo 'Starting workspace !'
        npx browser-sync start -s -w

        
ports:
  - port: 8000
  
