# Commands to start on workspace startup
tasks:
  - init: yarn install
    command: yarn build
             npx browser-sync start -s -w

# Ports to expose on workspace startup
ports:
  - port: 8000
    onOpen: open-preview
